//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FootHoodDBContext : DbContext
    {
        public FootHoodDBContext()
            : base("name=FootHoodDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblChat> tblChats { get; set; }
        public virtual DbSet<tblEquipment> tblEquipments { get; set; }
        public virtual DbSet<tblEquipmentInGame> tblEquipmentInGames { get; set; }
        public virtual DbSet<tblFeedback> tblFeedbacks { get; set; }
        public virtual DbSet<tblJoinRequest> tblJoinRequests { get; set; }
        public virtual DbSet<tblMessageSender> tblMessageSenders { get; set; }
        public virtual DbSet<tblPlayer> tblPlayers { get; set; }
        public virtual DbSet<tblPlayerInTeam> tblPlayerInTeams { get; set; }
        public virtual DbSet<tblPlayerRegisteredToGame> tblPlayerRegisteredToGames { get; set; }
        public virtual DbSet<tblRating> tblRatings { get; set; }
        public virtual DbSet<tblRatingOfGame> tblRatingOfGames { get; set; }
        public virtual DbSet<tblSetting> tblSettings { get; set; }
        public virtual DbSet<tblTeam> tblTeams { get; set; }
        public virtual DbSet<tblGame> tblGames { get; set; }
        public virtual DbSet<tblHotGamesMatch> tblHotGamesMatches { get; set; }
    }
}
