//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEquipmentInGame
    {
        public int GameSerialNum { get; set; }
        public int EquipmentSerialNum { get; set; }
        public int EquipmentInGameId { get; set; }
    
        public virtual tblEquipment tblEquipment { get; set; }
        public virtual tblGame tblGame { get; set; }
    }
}
