//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlayerRegisteredToGame
    {
        public string BringItems { get; set; }
        public int PlayerRegisteredToGameId { get; set; }
        public Nullable<bool> WaitOrNot { get; set; }
        public string EmailPlayer { get; set; }
        public int GameSerialNum { get; set; }
        public int GroupNumber { get; set; }
    
        public virtual tblPlayer tblPlayer { get; set; }
        public virtual tblGame tblGame { get; set; }
    }
}
