//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlayer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPlayer()
        {
            this.tblFeedbacks = new HashSet<tblFeedback>();
            this.tblJoinRequests = new HashSet<tblJoinRequest>();
            this.tblPlayerRegisteredToGames = new HashSet<tblPlayerRegisteredToGame>();
            this.tblPlayerInTeams = new HashSet<tblPlayerInTeam>();
            this.tblRatings = new HashSet<tblRating>();
            this.tblRatings1 = new HashSet<tblRating>();
            this.tblSettings = new HashSet<tblSetting>();
            this.tblTeams = new HashSet<tblTeam>();
            this.tblHotGamesMatches = new HashSet<tblHotGamesMatch>();
        }
    
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public int Phone { get; set; }
        public string Passcode { get; set; }
        public bool Gender { get; set; }
        public string PlayerCity { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string PlayerPicture { get; set; }
        public int Height { get; set; }
        public bool StrongLeg { get; set; }
        public int Stamina { get; set; }
        public string PreferredRole { get; set; }
        public string PreferredLocation { get; set; }
        public Nullable<int> OverallRating { get; set; }
        public Nullable<int> LastSearchRadius { get; set; }
        public Nullable<int> OTP { get; set; }
        public Nullable<double> LatitudeHomeCity { get; set; }
        public Nullable<double> LongitudeHomeCity { get; set; }
        public string TokenNotfication { get; set; }
        public int DistanceOfInvites { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFeedback> tblFeedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJoinRequest> tblJoinRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPlayerRegisteredToGame> tblPlayerRegisteredToGames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPlayerInTeam> tblPlayerInTeams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRating> tblRatings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRating> tblRatings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSetting> tblSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTeam> tblTeams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotGamesMatch> tblHotGamesMatches { get; set; }
    }
}
