//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlayerInTeam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPlayerInTeam()
        {
            this.tblMessageSenders = new HashSet<tblMessageSender>();
        }
    
        public int NumOfTimesEnteredTeam { get; set; }
        public string EmailPlayer { get; set; }
        public int TeamSerialNum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMessageSender> tblMessageSenders { get; set; }
        public virtual tblPlayer tblPlayer { get; set; }
        public virtual tblTeam tblTeam { get; set; }
    }
}
