//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRatingOfGame
    {
        public int RatingOfGameId { get; set; }
        public int RatingSerialNum { get; set; }
        public int GameSerialNum { get; set; }
    
        public virtual tblRating tblRating { get; set; }
        public virtual tblGame tblGame { get; set; }
    }
}
