//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRating
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRating()
        {
            this.tblRatingOfGames = new HashSet<tblRatingOfGame>();
        }
    
        public int RatingSerialNum { get; set; }
        public int PowerRating { get; set; }
        public int AttackRating { get; set; }
        public int DefenseRating { get; set; }
        public System.DateTime RatingDate { get; set; }
        public bool GameOrGenrel { get; set; }
        public string EmailofRatingPlayer { get; set; }
        public string EmailofRatedPlayer { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual tblPlayer tblPlayer { get; set; }
        public virtual tblPlayer tblPlayer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRatingOfGame> tblRatingOfGames { get; set; }
    }
}
