//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTeam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTeam()
        {
            this.tblPlayerInTeams = new HashSet<tblPlayerInTeam>();
            this.tblGames = new HashSet<tblGame>();
        }
    
        public int TeamSerialNum { get; set; }
        public string TeamName { get; set; }
        public string TeamPicture { get; set; }
        public int NumOfPlayers { get; set; }
        public bool IsPrivate { get; set; }
        public string RulesAndLaws { get; set; }
        public string EmailManager { get; set; }
    
        public virtual tblPlayer tblPlayer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPlayerInTeam> tblPlayerInTeams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGame> tblGames { get; set; }
    }
}
